export {default as Login} from './Login/Login'
export {default as Header} from './Header/Header'
export {default as Home} from './Home/Home'
export {default as Teacher} from './Teacher/Teacher'
export {default as ForgotPs} from './ForgotPs/ForgotPs'
export {default as Rest} from './Reset/Rest'
export {default as ProtectedRoute} from './ProtectedRoute/ProtectedRoute'